In [6]:
# 1) Combining a one and a two-dimensional NumPy Array 

import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([
    [4,5,6],
    [7,8,9]
])
res=np.vstack((arr2, arr1))
print(res)

[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [8]:
# 2) Flatten a 2d numpy array into 1d array

import numpy as np
arr1=np.array([
    [4,5,6],
    [7,8,9]
])

res=arr1.reshape(-1)
print(res)

[4 5 6 7 8 9]


In [9]:
#  3) Reverse a numpy array 
import numpy as np
arr=np.array([1,2,3,4,5])
res=np.flip(arr)
print(res)

[5 4 3 2 1]


In [ ]:
# 4) Practice operations like Get the maximum value from given array Get the minimum value from
#  given array 
import numpy as np
arr=np.array([1,2,3,4,5])
max=arr.max()
min=arr.min()
print("maximum element:",max)
print("minimum element:",min)
# Find the number of rows and columns of a given array using NumPy Select the elements from a 
# given array (each element and specific element) 
arr1=np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print("no. of rows and columns:",arr1.shape)
print(arr1[0,0] , arr1[0,1] , arr1[0,2] , arr1[0,3] ,arr1[1,0] ,arr1[1,1] , arr1[1,2] , arr1[1,3])

# Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing
#  arrays in Numpy
sum=0

for row in arr1:
    for e in row:
        sum=sum+e


print("sum:",sum)





maximum element: 5
minimum element: 1
no. of rows and columns: (2, 4)
1 2 3 4 5 6 7 8
36


In [ ]:
#  5) Iterate 3D array using for loop and nditer
import numpy as np
arr = np.array([[[1, 2],
                 [3, 4]],

                [[5, 6],
                 [7, 8]]])

for i in arr:
    for j in i:
        for k in j:
            print(k)

for i in np.nditer(arr):
    print(i)


1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [24]:
#  6) Study the following program 
# import numpy as np 
# # create a numpy 1d-arrays 
# arr1 = np.array([3, 4])
#  arr2 = np.array([1, 0])
#  # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays
import numpy as np
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
avg = (arr1 + arr2) / 2
print("Average array:")
print(avg)

mean = np.mean(avg)
print("Mean:", mean)

median = np.median(avg)
print("Median:", median)

mode = np.bincount(avg.astype(int).flatten()).argmax()
print("Mode:", mode)

Average array:
[[3. 4.]
 [5. 6.]]
Mean: 4.5
Median: 4.5
Mode: 3
