In [ ]:
#1) Create numpy array and perform following operation 
# > Convert 1D array to 2D 
import numpy as np
arr= np.array([1,2,3,4,5,6])
res= arr.reshape(2,3)
print(res)
# > Print Array Attributes(Like shape, dimenssion, data type, itemsize) 
print("shape:",res.shape)
print("dimensions:",res.ndim)
print("data type:",res.dtype)
print("itemsize:",arr.itemsize)


[[1 2 3]
 [4 5 6]]
shape: (2, 3)
dimensions: 2
data type: int64
itemsize: 8


In [11]:
# > Create a 3×3 NumPy array of all 9 
arr1= np.full((3,3),9)
print(arr1)

# > Create a 1D array of 10 evenly spaced values between 25 and 125 
print(np.linspace(25,125,10))

[[9 9 9]
 [9 9 9]
 [9 9 9]]
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [12]:
# > Convert a Python list into a NumPy array 
l=[6,7,8]
print(np.array(l))

# > Reverse a 1D NumPy array 
arr=np.array([1,2,3,4,5])
print("reversed:",arr[-1::-1])

[6 7 8]
reversed: [5 4 3 2 1]


In [13]:
# > Create a 4×4×3 array and extract value at its second set, first row and last column 

arr = np.arange(48).reshape(4, 4, 3)
print(arr)
print(arr[1, 0, 2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
14


In [15]:
# > Create a 4×4 and Extract Odd Rows and Even Columns 
arr=np.arange(16).reshape(4,4)
print(arr)

result = arr[1::2, ::2]

print("Odd Rows and Even Columns:")
print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Odd Rows and Even Columns:
[[ 4  6]
 [12 14]]


In [16]:
# > Slice the first two rows and first two columns of econd set from a 4×4×3 array 
arr = np.arange(48).reshape(4, 4, 3)
result = arr[1, :2, :2]
print(result)

[[12 13]
 [15 16]]


In [ ]:
# > Replace all odd numbers in a NumPy array with -1 by itterating using for loop 
# [[23, 56, 78, 93], [71, 82,13, 24]] 
arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1

print(arr)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [20]:
# > Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] 
arr = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(arr)
print(indices)
# > Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element 
# by element. Multiply two NumPy arrays element by element. 
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
addition = arr1 + arr2
multiplication = arr1 * arr2

print("Addition:", addition)
print("Multiplication:", multiplication)
# > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = 
# [10,40,37]
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)

print("Dot Product:", dot_product)

(array([0, 2, 4, 6]),)
Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
Dot Product: 1875
