In [14]:
#1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], 
# [np.nan, -8, 0, 94]] 

import numpy as np
arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])
print(arr)
arr = np.nan_to_num(arr, nan=0)
print(arr)
print(arr.T)


[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [2]:
# 2) Move axes of 3D array to new positions 
import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])
print(arr.shape)
new_arr = np.moveaxis(arr, 0, 1)
print(new_arr)
print(new_arr.shape)

(2, 4)
[[   6.   nan]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]
(4, 2)


In [5]:
# 3) Replace NaN values with average of columns
import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

mean = np.nanmean(arr, axis=0)

inds = np.where(np.isnan(arr))

arr[inds] = np.take(mean, inds[1])

print(arr)


[[   6.   -8.   73. -110.]
 [   6.   -8.    0.   94.]]


In [7]:
# 4) Replace negative value with zero in numpy array using replace

import numpy as np
arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])
arr[arr < 0] = 0
print(arr)

[[ 6.  0. 73.  0.]
 [nan  0.  0. 94.]]
